# This workflow will build a Java project with Maven

name: Models API Tests

on:
  workflow_dispatch
#  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
#      - uses: actions/checkout@v4

      - name: Checkout of TEST repo
        uses: actions/checkout@v4

      - name: Checkout of DEV repo
        uses: actions/checkout@v4
        with:
          repository: openinnovationai/recruiting-qa-challenge
          path: recruiting-qa-challenge

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
         python-version: '3.9'

      - name: Install Python dependencies and Run Python server script
        run: |
          cd recruiting-qa-challenge
          pip install -r requirements.txt
          fastapi dev application.py &
          sleep 100 &&
          cd .. &&
          ./mvnw clean test

      - name: Get Allure history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Create Allure Report
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history